//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TerminalSecurity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Посетитель
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Посетитель()
        {
            this.Авторизация = new HashSet<Авторизация>();
            this.Посещающие = new HashSet<Посещающие>();
            this.Черный_список = new HashSet<Черный_список>();
        }
    
        public int Код_посетителя { get; set; }
        public string Фамилия { get; set; }
        public string Имя { get; set; }
        public string Отчество { get; set; }
        public string Номер_телефона { get; set; }
        public string Email { get; set; }
        public System.DateTime Дата_рождения { get; set; }
        public int Код_организации { get; set; }
        public int Серия_паспорта { get; set; }
        public int Номер_паспорта { get; set; }
        public byte[] Фотография { get; set; }
        public byte[] Скан_паспорта { get; set; }
        public string Примечания { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Авторизация> Авторизация { get; set; }
        public virtual Организация Организация { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Посещающие> Посещающие { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Черный_список> Черный_список { get; set; }
    }
}
