//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TerminalСommon
{
    using System;
    using System.Collections.Generic;
    
    public partial class Пропуск
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Пропуск()
        {
            this.Заявка = new HashSet<Заявка>();
        }
    
        public int Код_пропуска { get; set; }
        public System.DateTime Срок_начала_действия { get; set; }
        public System.DateTime Срок_окончания_действия { get; set; }
        public string Цель_посещения { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Заявка> Заявка { get; set; }
    }
}
