//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hranitel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HranitelProEntities : DbContext
    {
        public HranitelProEntities()
            : base("name=HranitelProEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Авторизация> Авторизация { get; set; }
        public virtual DbSet<Группа> Группа { get; set; }
        public virtual DbSet<Заявка> Заявка { get; set; }
        public virtual DbSet<Организация> Организация { get; set; }
        public virtual DbSet<Отдел> Отдел { get; set; }
        public virtual DbSet<Подразделение> Подразделение { get; set; }
        public virtual DbSet<Посетитель> Посетитель { get; set; }
        public virtual DbSet<Посещающие> Посещающие { get; set; }
        public virtual DbSet<Пропуск> Пропуск { get; set; }
        public virtual DbSet<Сотрудник> Сотрудник { get; set; }
        public virtual DbSet<Статус> Статус { get; set; }
        public virtual DbSet<Тип_заявки> Тип_заявки { get; set; }
        public virtual DbSet<Черный_список> Черный_список { get; set; }
    }
}
