//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hranitel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Заявка_на_личное_посещение
    {
        public int Код_личного_посещения { get; set; }
        public int Код_пропуска { get; set; }
        public int Код_подразделения { get; set; }
        public int Код_сотрудника { get; set; }
        public int Код_посетителя { get; set; }
        public System.DateTime Дата_создания { get; set; }
        public string Статус { get; set; }
    
        public virtual Подразделение Подразделение { get; set; }
        public virtual Посетитель Посетитель { get; set; }
        public virtual Пропуск Пропуск { get; set; }
        public virtual Сотрудник Сотрудник { get; set; }
    }
}
