//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hranitel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Заявка
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Заявка()
        {
            this.Посещающие = new HashSet<Посещающие>();
        }
    
        public int Код_заявки { get; set; }
        public int Код_типа_заявки { get; set; }
        public int Код_пропуска { get; set; }
        public int Код_подразделения { get; set; }
        public int Код_сотрудника { get; set; }
        public System.DateTime Дата_создания { get; set; }
        public Nullable<System.DateTime> Дата_и_время_посящения { get; set; }
        public int Код_статуса { get; set; }
        public string Причина_отказа { get; set; }
    
        public virtual Подразделение Подразделение { get; set; }
        public virtual Пропуск Пропуск { get; set; }
        public virtual Сотрудник Сотрудник { get; set; }
        public virtual Статус Статус { get; set; }
        public virtual Тип_заявки Тип_заявки { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Посещающие> Посещающие { get; set; }
    }
}
