//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hranitel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Посещающие
    {
        public int Код_посещающих { get; set; }
        public int Код_заявки { get; set; }
        public int Код_посетителя { get; set; }
        public Nullable<int> Код_группы { get; set; }
    
        public virtual Группа Группа { get; set; }
        public virtual Заявка Заявка { get; set; }
        public virtual Посетитель Посетитель { get; set; }
    }
}
